 %%%% plot hwhwm for sf, tf, orient comparing tuning curves generated by...
%%%% ... high locomotion vs. low locomotion trials
%
% updated 2023/5/24

%% load data
% load('F:\analyses\cells20-9-21')

compname = getenv('COMPUTERNAME');
switch compname
    case 'MSI' % AM laptop
        cells_data_file = 'C:\Users\amsme\Downloads\wustl_paper\analyses\cells23-5-20.mat';
    case 'DESKTOP-H739EDS' % AB lab thermaltake
        cells_data_file = 'F:\analyses\cells21-1-16.mat';
end

close all
clear ops groupstats
ops.meets_criteria = true(height(roitable),1); % reset meets_criteria

if ~exist('roitable','var') % if cells data not loaded yet
    loadtic = tic;
    load(cells_data_file,'filetable','roitable') % takes a while to load full table
%     load(cells_data_file,'filetable','roitable_full') % roitable_full contains more variables than we need for computing stats in this script
    cells_file_loadtime = toc(loadtic)
    
    % add a 'responsive' variable, which is true if anovap < 0.05 for all conditions (including no-stim) within either sf, tf, or orient
    %%%% responsivity metric from: ohki ea 2005 - Functional imaging with cellular resolution reveals precise micro-architecture in visual cortex
    roitable.rspv = roitable.sf_sgnf_rspv | roitable.tf_sgnf_rspv | roitable.orient_sgnf_rspv;
    
     %%% add subject-relative day index to filetable and roitable
    add_sub_day_ind(); 
end

%% parameters

ops.save_fig = 0;
    ops.savename = 'F:\thesis\figs\2020-9-15\fig s1 -- hwhm_highloc_vs_lowloc';

% ops.stimpars_to_plot = {'sf', 'tf', 'orient'}; 
% ops.stimpars_to_plot = {'sf'}; 
%     ops.ylim = [0 1.7]; %%% for physiology supp figure violin plot
%     ops.violin_bandwidth = 0.05; %%%  for physiology supp figure violin plot
% ops.stimpars_to_plot = {'tf'}; 
%     ops.ylim = [0 13]; %%% for physiology supp figure violin plot
%     ops.violin_bandwidth = 0.4; %%%  for physiology supp figure violin plot
ops.stimpars_to_plot = {'orient'}; 
    ops.ylim = [0 120]; %%% for physiology supp figure violin plot
    ops.violin_bandwidth = 5; %%%  for physiology supp figure violin plot

%%%% require significant tuning for variable of interest
% ops.meets_criteria = ops.meets_criteria & roitable{:, [stimparam, '_anovap']} < 0.05; 
% ops.meets_criteria = ops.meets_criteria & [ roitable{:,'sf_sgnf'} | roitable{:,'tf_sgnf'} | roitable{:,'orient_sgnf'} ]; 

% ops.meets_criteria = ops.meets_criteria & roitable.pakan_loc_sgnf; 
ops.meets_criteria = ops.meets_criteria & roitable.stim_overlap_frac > 0.00; % stim on RF
ops.meets_criteria = ops.meets_criteria & any(roitable.quantile == [1 2 5 6],2); %%% exclude middle third of quantiles

require_sgnf_tuning_for_each_stimpar = 1; % cells tested for sf_hwhm must be sf_sgnf, tf_hwhm must be tf_sgnf, orient_hwhm orient_sgnf

% violin options
ops.use_violin_plot = 1; % make violin plot instead of bargraphs
    ops.overlay_violin_with_boxplot = 1;
    ops.violin_median_color = [];
        % ops.violin_median_color = 'k';
    % ops.violin_mean_color = [];
        ops.violin_mean_color = 'r'; 
%     ops.violin_face_color= [1 0.5 0]; 
    ops.violin_face_color= [0.5 0.5 0.5]; 
    ops.violin_edge_color = [0 0 0 ];
    ops.violin_linewidth = 2;
    ops.violin_xvals = [1 1.7]; 
    ops.violin_xlim = [0.6 2.0]; 
    ops.violin_xaxis_visible = 0; 
    ops.violin_axis_thickness = 2.5;

% figure options
ops.newfig = 1; 
ops.ebar_thickness = 3; 
ops.ebar_cap_size = 6;
ops.ebar_color = [0 0 0]; 
ops.font_name = 'Arial'; 
ops.axis_thickness = 3.5;
ops.bar_quant_colors = repmat(linspace(0.08,0.86,6)',1,3);
    ops.quant_bar_width = 0.9; %%% bar width for quantile plotting only
ops.bar_one_color = [0.5 0.5 0.5]; 
ops.bar_quant_border_color = [1 1 1]; 
ops.bargraph_line_width = 4;
ops.axis_font_bold = 1; % font bold or not bold
ops.axis_font_size = 19; %%%% in thesis hwhm locm plots, size 13 was used
ops.xlim = [0.3 2.7]; 
ops.subplot_row_col = [1 3]; 
ops.subplot_spacing_yx = [0.1 0.13]; 

%     ops.ylim = [0.0 0.16]; 

% ops.fig_outerposition = [0.05 0.05 0.22 0.60]; % [left bottom width height]...
%     ops.fig_outerposition = [0.05 0.05 0.42 0.65]; % [left bottom width height]... 
% ops.fig_outerposition = [0.05 0.05 0.7 0.32]; % [left bottom width height]... 
ops.fig_outerposition = [0.45 0.15 0.22 0.60]; % [left bottom width height]... for paper, physiology supp figure violin plots

    
%% plotting 
    
n_stimpars = length(ops.stimpars_to_plot); 
groupstats = table;
if ops.newfig; hfig = figure('units','normalized','outerposition',ops.fig_outerposition); end
    
for ipar = 1:n_stimpars
    %%%% get values to plot
    clear matchrows
    matchrows = ops.meets_criteria; 
    
    this_stimpar = ops.stimpars_to_plot{ipar};
    groupstats.stimpar{ipar} = this_stimpar; 
    if require_sgnf_tuning_for_each_stimpar
        matchrows = matchrows & roitable{:,[this_stimpar, '_sgnf']}; % require tuning for this specific stimpar
    end
    groupstats.matchrows{ipar} = matchrows; 
    groupstats.hwhm_low_locm{ipar} = roitable{matchrows, [this_stimpar, '_hwhm_low_locm']};
    groupstats.hwhm_low_locm{ipar} = groupstats.hwhm_low_locm{ipar}( ~isnan(groupstats.hwhm_low_locm{ipar}) ); % remove NaNs
    groupstats.hwhm_high_locm{ipar} = roitable{matchrows, [this_stimpar, '_hwhm_high_locm']};
    groupstats.hwhm_high_locm{ipar} = groupstats.hwhm_high_locm{ipar}( ~isnan(groupstats.hwhm_high_locm{ipar}) ); % remove NaNs
    groupstats.n_lowloc(ipar) = length(groupstats.hwhm_low_locm{ipar}); 
    groupstats.n_highloc(ipar) = length(groupstats.hwhm_high_locm{ipar}); 
    groupstats.mean_lowloc(ipar) = mean(groupstats.hwhm_low_locm{ipar}); 
    groupstats.mean_highloc(ipar) = mean(groupstats.hwhm_high_locm{ipar});
    groupstats.sem_lowloc(ipar) = std(groupstats.hwhm_low_locm{ipar}) / sqrt(groupstats.n_lowloc(ipar)); % standard error
    groupstats.sem_highloc(ipar) = std(groupstats.hwhm_high_locm{ipar}) / sqrt(groupstats.n_highloc(ipar)); % standard error
    
    %%%% do plotting
    means_to_plot = [groupstats.mean_lowloc(ipar), groupstats.mean_highloc(ipar)];
    sems_to_plot = [groupstats.sem_lowloc(ipar), groupstats.sem_highloc(ipar)];
    

    if ops.use_violin_plot 
        hwhm_vals_to_plot = [groupstats.hwhm_low_locm(ipar), groupstats.hwhm_high_locm(ipar)]; 
        if isfield(ops, 'violin_bandwidth') % if bandwidth was specified
            [hviolin,hleg,group_means,group_medians,bw] = violin(hwhm_vals_to_plot,'bw',ops.violin_bandwidth,'mc',ops.violin_mean_color,'medc',ops.violin_median_color,...
                'facecolor',ops.violin_face_color,'edgecolor',ops.violin_edge_color,'x',ops.violin_xvals);
        elseif ~isfield(ops, 'violin_bandwidth') % use default bandwidth if not specified
            [hviolin,hleg,group_means,group_medians,bw] = violin(hwhm_vals_to_plot,'mc',ops.violin_mean_color,'medc',ops.violin_median_color,...
                'facecolor',ops.violin_face_color,'edgecolor',ops.violin_edge_color,'x',ops.violin_xvals);      
        end

        hax = gca;
        hax.FontName = ops.font_name;
        hax.FontSize = ops.axis_font_size;
        if ops.axis_font_bold; set(gca,'FontWeight','bold'); end
        hax.LineWidth = ops.violin_axis_thickness; 
        for iplot = 1:length(hviolin); hviolin(iplot).LineWidth = ops.violin_linewidth; end
        set(gca,'xtick',[])
        if ~ops.violin_xaxis_visible; hax.XAxis.Visible = 'off'; end
        hleg.Visible = 'off'; % turn legend off
        if isfield(ops,'ylim'); ylim(ops.ylim); end
        if isfield(ops,'violin_xlim'); xlim(ops.violin_xlim); end
        set(gca,'Box','off')
        set(gca,'LooseInset',get(gca,'TightInset')+[0 0 0.005 0]) % crop borders



    elseif ~ops.use_violin_plot % make bargraphs instead of violin
        subtightplot(ops.subplot_row_col(1), ops.subplot_row_col(2), ipar, ops.subplot_spacing_yx)   
        barhandle = bar(means_to_plot); 
        barhandle.FaceColor = ops.bar_one_color; 
        barhandle.LineWidth = ops.bargraph_line_width; 
        hax = gca; 
        hax.XTick = []; 
        
        hold on
    
        ebar = errorbar(1:2,means_to_plot,sems_to_plot,'.','Color',ops.ebar_color);
        hold off
        hax.FontName = ops.font_name;
        hax.FontSize = ops.axis_font_size;
        hax.LineWidth = ops.axis_thickness;
        ebar.LineWidth = ops.ebar_thickness; % set errorbar line width
        ebar.Color = ops.ebar_color; % set errorbar line color
        ebar.CapSize = ops.ebar_cap_size; 
        if isfield(ops,'ylim'); ylim(ops.ylim); end
        if isfield(ops,'xlim'); xlim(ops.xlim); end
        if ops.axis_font_bold; set(gca,'FontWeight','bold'); end
        set(gca,'LooseInset',get(gca,'TightInset')+[0 0 0.005 0]) % crop borders
        set(gca,'Box','off')
            
    end

    % print results
    this_stimpar
    [~, p_lowloc_vs_highloc] = ttest2(groupstats.hwhm_low_locm{ipar}, groupstats.hwhm_high_locm{ipar}) %%% t-test

end

%% save plot
if ops.save_fig
    if exist(savename,'file')
        delete(ops.savename)
    end
    saveas(hfig, ops.savename, 'svg')
end